### ISSUE TITLE
Gem does not work on Windows and latest version of Ruby 1.9.3 and Ruby 2.0.0

### ISSUE THREAD

**Issue by mamontov-cpp** [banister/devil#15]
In new versions of Ruby on Win32 gem installs fine, but any references to it give the following errors:

```
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require':
cannot load such file -- C:/Ruby193/lib/ruby/gems/1.9.1/gems/devil-0.1.9.5-x86-m
ingw32/lib/devil.so (LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:i
n `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/devil-0.1.9.5-x86-mingw32/lib/d
evil.rb:15:in `rescue in <top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/devil-0.1.9.5-x86-mingw32/lib/d
evil.rb:8:in `<top (required)>'
```

**Comment by mamontov-cpp** [comment]
Solved this problems by creating a [fork](https://github.com/ahiddenseeker/). Seems to work for me. Could somebody do a code review and point to an errors (if any)?

**Comment by andresmafra** [comment]
For me it isnt working. How can I proceed?
